// ─── Resume Templates ─────────────────────────────────────────────────────────
// Each template is a partial settings object. applyTemplate() merges these
// into the active resume's settings via updateSetting().

export const TEMPLATES = [
  {
    id: 'classic',
    name: 'Classic',
    description: 'Timeless and clean',
    accentColor: '#6366f1',
    borderColor: '#e5e7eb',
    fontCategory: 'sans',
    fontFamily: 'Source Sans Pro',
    fontSize: 9.5,
    lineHeight: 1.15,
    marginX: 12,
    marginY: 12,
    headingStyle: 'underline',
    headingCapitalization: 'uppercase',
    headingSize: 'M',
    headerLayout: 'classic',
    headerPosition: 'top',
    accentHeadings: false,
    accentHeadingLine: true,
    accentName: false,
    accentJobTitle: false,
    columns: 'one',
    sidebarBgColor: '',
    sidebarTextColor: '',
    contactLayout: 'inline',
    headerBgColor: '',
    headerTextColor: '',
  },
  {
    id: 'executive',
    name: 'Executive',
    description: 'Authoritative serif',
    accentColor: '#334155',
    borderColor: '#cbd5e1',
    fontCategory: 'serif',
    fontFamily: 'Lora',
    fontSize: 9.5,
    lineHeight: 1.2,
    marginX: 14,
    marginY: 14,
    headingStyle: 'bold',
    headingCapitalization: 'capitalize',
    headingSize: 'M',
    headerLayout: 'classic',
    headerPosition: 'top',
    accentHeadings: false,
    accentHeadingLine: false,
    accentName: false,
    accentJobTitle: false,
    columns: 'one',
    sidebarBgColor: '',
    sidebarTextColor: '',
    contactLayout: 'inline',
    headerBgColor: '',
    headerTextColor: '',
  },
  {
    id: 'modern',
    name: 'Modern',
    description: 'Minimal two-column',
    accentColor: '#0f766e',
    borderColor: '#ccfbf1',
    fontCategory: 'sans',
    fontFamily: 'Jost',
    fontSize: 9,
    lineHeight: 1.15,
    marginX: 10,
    marginY: 10,
    headingStyle: 'plain',
    headingCapitalization: 'uppercase',
    headingSize: 'S',
    headerLayout: 'classic',
    headerPosition: 'top',
    accentHeadings: true,
    accentHeadingLine: false,
    accentName: false,
    accentJobTitle: true,
    columns: 'two',
    sidebarBgColor: '',
    sidebarTextColor: '',
    contactLayout: 'inline',
    headerBgColor: '',
    headerTextColor: '',
  },
  {
    id: 'creative',
    name: 'Creative',
    description: 'Bold & expressive',
    accentColor: '#be185d',
    borderColor: '#fce7f3',
    fontCategory: 'serif',
    fontFamily: 'Playfair Display',
    fontSize: 9.5,
    lineHeight: 1.2,
    marginX: 12,
    marginY: 12,
    headingStyle: 'filled',
    headingCapitalization: 'capitalize',
    headingSize: 'M',
    headerLayout: 'bold',
    headerPosition: 'top',
    accentHeadings: false,
    accentHeadingLine: false,
    accentName: true,
    accentJobTitle: false,
    columns: 'one',
    sidebarBgColor: '',
    sidebarTextColor: '',
    contactLayout: 'inline',
    headerBgColor: '',
    headerTextColor: '',
  },
  {
    id: 'compact',
    name: 'Compact',
    description: 'Dense, information-rich',
    accentColor: '#374151',
    borderColor: '#e5e7eb',
    fontCategory: 'sans',
    fontFamily: 'Barlow',
    fontSize: 8.5,
    lineHeight: 1.1,
    marginX: 10,
    marginY: 10,
    headingStyle: 'leftbar',
    headingCapitalization: 'uppercase',
    headingSize: 'S',
    headerLayout: 'compact',
    headerPosition: 'top',
    accentHeadings: false,
    accentHeadingLine: false,
    accentName: false,
    accentJobTitle: false,
    columns: 'mix',
    sidebarBgColor: '',
    sidebarTextColor: '',
    contactLayout: 'inline',
    headerBgColor: '',
    headerTextColor: '',
  },
  {
    id: 'academic',
    name: 'Academic',
    description: 'Traditional & formal',
    accentColor: '#1D4ED8',
    borderColor: '#dbeafe',
    fontCategory: 'serif',
    fontFamily: 'EB Garamond',
    fontSize: 10,
    lineHeight: 1.25,
    marginX: 14,
    marginY: 14,
    headingStyle: 'centered',
    headingCapitalization: 'capitalize',
    headingSize: 'M',
    headerLayout: 'centered',
    headerPosition: 'top',
    accentHeadings: false,
    accentHeadingLine: true,
    accentName: false,
    accentJobTitle: false,
    columns: 'one',
    sidebarBgColor: '',
    sidebarTextColor: '',
    contactLayout: 'inline',
    headerBgColor: '',
    headerTextColor: '',
  },
  {
    id: 'minimal',
    name: 'Minimal',
    description: 'Ultra-clean whitespace',
    accentColor: '#6b7280',
    borderColor: '#f3f4f6',
    fontCategory: 'sans',
    fontFamily: 'Nunito',
    fontSize: 9.5,
    lineHeight: 1.2,
    marginX: 16,
    marginY: 16,
    headingStyle: 'plain',
    headingCapitalization: 'capitalize',
    headingSize: 'S',
    headerLayout: 'classic',
    headerPosition: 'top',
    accentHeadings: false,
    accentHeadingLine: false,
    accentName: false,
    accentJobTitle: false,
    columns: 'one',
    sidebarBgColor: '',
    sidebarTextColor: '',
    contactLayout: 'inline',
    headerBgColor: '',
    headerTextColor: '',
  },
  {
    id: 'bold',
    name: 'Bold',
    description: 'High impact, confident',
    accentColor: '#b91c1c',
    borderColor: '#fee2e2',
    fontCategory: 'sans',
    fontFamily: 'Rubik',
    fontSize: 9.5,
    lineHeight: 1.15,
    marginX: 12,
    marginY: 12,
    headingStyle: 'underline',
    headingCapitalization: 'uppercase',
    headingSize: 'L',
    headerLayout: 'bold',
    headerPosition: 'top',
    accentHeadings: false,
    accentHeadingLine: true,
    accentName: true,
    accentJobTitle: true,
    columns: 'one',
    sidebarBgColor: '',
    sidebarTextColor: '',
    contactLayout: 'inline',
    headerBgColor: '',
    headerTextColor: '',
  },
  // ── NEW: Sidebar layout ───────────────────────────────────────────────────────
  {
    id: 'atlantic',
    name: 'Atlantic',
    description: 'Navy sidebar with photo',
    accentColor: '#60a5fa',
    borderColor: '#bfdbfe',
    fontCategory: 'sans',
    fontFamily: 'Jost',
    fontSize: 9.5,
    lineHeight: 1.2,
    marginX: 0,
    marginY: 0,
    headingStyle: 'plain',
    headingCapitalization: 'uppercase',
    headingSize: 'S',
    headerLayout: 'sidebar',
    headerPosition: 'left',
    accentHeadings: true,
    accentHeadingLine: false,
    accentName: false,
    accentJobTitle: false,
    columns: 'one',
    sidebarBgColor: '#1e3a5f',
    sidebarTextColor: '#ffffff',
    contactLayout: 'stacked',
    headerBgColor: '',
    headerTextColor: '',
  },
  // ── NEW: Two-tone colored header ─────────────────────────────────────────────
  {
    id: 'harvard',
    name: 'Harvard',
    description: 'Crimson header, serif body',
    accentColor: '#9f1239',
    borderColor: '#fecdd3',
    fontCategory: 'serif',
    fontFamily: 'EB Garamond',
    fontSize: 10,
    lineHeight: 1.25,
    marginX: 14,
    marginY: 14,
    headingStyle: 'underline',
    headingCapitalization: 'uppercase',
    headingSize: 'M',
    headerLayout: 'classic',
    headerPosition: 'top',
    accentHeadings: false,
    accentHeadingLine: true,
    accentName: false,
    accentJobTitle: false,
    columns: 'one',
    sidebarBgColor: '',
    sidebarTextColor: '',
    contactLayout: 'inline',
    headerBgColor: '#7c2d36',
    headerTextColor: '#ffffff',
  },
]
